# Generated by Django 3.2.9 on 2021-12-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='blog_created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='blog_body',
            field=models.CharField(default='', max_length=1000000),
        ),
        migrations.AddField(
            model_name='post',
            name='blog_image',
            field=models.ImageField(default='', upload_to='{%static "images/posts" %}'),
        ),
        migrations.AddField(
            model_name='post',
            name='blog_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='blog_writer',
            field=models.CharField(default='', max_length=15),
        ),
    ]
