# Generated by Django 3.2.9 on 2021-12-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_alter_post_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_feature_yesno',
            field=models.BooleanField(default='False'),
        ),
    ]
