# Generated by Django 3.2.9 on 2021-12-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_post_blog_feature_yesno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='blog_feature_yesno',
            new_name='blog_feature',
        ),
        migrations.AddField(
            model_name='post',
            name='editors_choice',
            field=models.BooleanField(default='False'),
        ),
    ]
